---
title: "Untitled"
output: html_document
date: "2024-03-11"
---

```{r setup, echo = FALSE, message = FALSE, warning=FALSE}

set.seed(100)
knitr::opts_chunk$set(fig.width=10, fig.height=8) 
library(dplyr)
#remotes::install_github("tidymass/massdataset")
library(massdataset)
library(massstat)
library(metpath)
library(massqc)
library(ggfortify)
#install.packages("factoextra")
library(factoextra)
library(ggplot2)
library(tidygraph)
library(RColorBrewer)
library(stringr)
library(KEGGREST)
library(clusterProfiler)
library(data.table)
library(igraph)
## load the saved object created from tidyMassObjectGeneration_serum.Rmd which includes some filtering and preprocessing before the actual analysis and data viz is done
load("/Users/apulvino/serum_metabolomics/stat_analysis/object2")
#object <- readRDS("/Users/apulvino/serum_metabolomics/stat_analysis/object.rds")

object

pca_object =
object %>%
  scale() %>%
  run_pca()
#pca_object$rotation

#pca_score_plot(object,
#               pca_object,
#               color_by = "group",
#               loadings = FALSE) +
#  ggsci::scale_fill_lancet() +
#  ggsci::scale_color_lancet()
#dev.off()

#tiff("qual2spca.tiff", units="in", width=8.5, height=5, res=300)
object %>%
  `+`(1) %>% 
  log %>% 
  scale %>%
  massqc_pca(color_by = "group", frame = FALSE)

#tiff("qual2spca.tiff", units="in", width=8.5, height=5, res=300)
object %>%
  `+`(1) %>% 
  log %>% 
  scale %>%
  massqc_pca(color_by = "group") #+
  #ggsci::scale_fill_lancet()
#dev.off()

object %>%
  `+`(1) %>%
  log %>%
  scale %>%
  massqc_pca(color_by = "group", line = FALSE) +
  scale_fill_manual(values = c(hum="#1b9e77",mac="#a6761d",sqm="#666666")) +
  scale_color_manual(values = c(hum="#1b9e77",mac="#a6761d",sqm="#666666")) +
  #guides(
  #  fill = guide_legend(override.aes = list(colour = NA, stroke = 0)),
  #  color = guide_legend(override.aes = list(stroke = 0))
  #)+ 
  #geom_point(shape = 16, size = 3, alpha = 0.05) +
  #theme(legend.key = element_rect(fill = "transparent", colour = "transparent")) +
  theme(axis.line.x = element_line(size = 0.5, linetype = "solid", colour = "black"), 
        axis.line.y = element_line(size = 0.5, linetype = "solid", colour = "black"),
        axis.ticks=element_blank(),
        panel.background=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        legend.position = "none"
        )+ 
  annotate("text", x = 0.30, y = 0.75, label = "sqm", color = "#666666") +
  annotate("text", x = -0.30, y = 0.40, label = "mac", color = "#a6761d") +
  annotate("text", x = 0.60, y = 0.50, label = "hum", color = "#1b9e77")

exp_data <- object@expression_data
exp_data$variable_id <- rownames(exp_data)
anno_data <- object@annotation_table
peak_table <- merge(anno_data, exp_data, by = "variable_id")
write_tsv(peak_table, "/Users/apulvino/4nSerMetabol.tsv")




```



```{r, group PERMANOVA}

# ### just make sure you have metadata first, run cecal_shotgun.Rmd first 2 blocks and that will give you metadata2 variable needed
# ### for all three groups, determine significance of term "group" effect
dimnames <- c("mac01","mac02","mac03","mac04","mac05","mac06","mac07","mac08",
              "sqm10","sqm11","sqm12","sqm13","sqm16","sqm17","sqm18",
              "hum19", "hum20","hum21","hum22","hum23","hum24")
#### ALL, 3-group pw comparison
 sample_distance <-
   as.matrix(dist_mass_dataset(x = object, margin = "sample", method = "manhattan"))
#rownames(sample_distance) <- dimnames
#colnames(sample_distance) <- dimnames
result <- metadata2 %>% filter(!sample %in% c("sqm9","sqm14", "sqm15", "hum25", "hum26"))
mat_cleaned <- sample_distance[
  !grepl("Ben-Ant-20240228-09|Ben-Ant-20240228-1[4-5]|Ben-Ant-20240228-2[5-6]", rownames(sample_distance)),
  !grepl("Ben-Ant-20240228-09|Ben-Ant-20240228-1[4-5]|Ben-Ant-20240228-2[5-6]", colnames(sample_distance)),
  drop = FALSE
]
print("global (all three groups) serum metabolome dataset permanova for effect of group")
adonis2(mat_cleaned ~ group, data = result)



```


## SIRIUS classification (for database-free metabolite classification and FELLA enrichment)

```{r }

library(tidyverse)
library(stats)
library(ggplot2)
library(scales)
library(purrr)
library(dplyr)
############ ATTEMPTING TO MERGE WITH TIDYMASS THE SIRIUS OUTPUT FOR GROUPWISE ANALYSIS WITH RESULTS
############## THIS IS VERY CLOSE AND WOULD BE EASY TO FINISH
# # #download from SIRIUS run on quest to computer
# df <- read_tsv("/Users/apulvino/serum_metabolomics/canopus_formula_summary_all.tsv")
# # 
# # # 1. Clean Canopus ID to isolate mappingFeatureId
# canopus_clean <- canopus_formula %>%
#   mutate(variable_id = str_remove(mappingFeatureId, ".*UNKNOWN_"))
# 
# # # 2. Merge with tidymass object using mappingFeatureId == alignedFeatureId
# merged <- left_join(object@variable_info, canopus_clean, by = "variable_id")

# Your full dataset
df_free <- read.delim("/Users/apulvino/serum_metabolomics/sirius_results/dualion_canopus_formula_summary_all.tsv",
                     sep = "\t", stringsAsFactors = FALSE, header = TRUE) 
df_free_clean <- df_free %>% filter(!pmap_lgl(., ~ any(c(...) == colnames(df_free))))
# Pairs of (class_col, prob_col) to analyze and plot
classification_cols <- list(
  c("NPC.pathway", "NPC.pathway.Probability"),
  c("NPC.superclass", "NPC.superclass.Probability"),
  c("NPC.class", "NPC.class.Probability"),
  c("ClassyFire.superclass", "ClassyFire.superclass.probability"),
  c("ClassyFire.class", "ClassyFire.class.Probability"),
  c("ClassyFire.subclass", "ClassyFire.subclass.Probability"),
  c("ClassyFire.level.5", "ClassyFire.level.5.Probability"),
  c("ClassyFire.most.specific.class", "ClassyFire.most.specific.class.Probability")
)

plot_class_enrichment <- function(df, class_col, prob_col, min_count = 5, conf_thresh = 0.9) {
  ##ensures prob col and class col are evaluated as numeric/string
  df <- df %>%
    mutate(
      !!sym(prob_col) := as.numeric(.data[[prob_col]]),
      !!sym(class_col) := as.character(.data[[class_col]])
    )
  ##filter missing vals group by class and compute median probability column
  summary_df <- df %>%
    filter(!is.na(.data[[class_col]]), !is.na(.data[[prob_col]])) %>%
    group_by(!!sym(class_col)) %>%
    summarise(
      n = n(),
      median_prob = median(.data[[prob_col]], na.rm = TRUE),
      .groups = "drop"
    ) %>%
    ##filter for compounds in common classes and high_conf = TRUE (if prob for compound class is greater than median)
    ##then we do log2 ratio to plot data in fold change style for relative enrichment measure
    filter(n >= min_count) %>%
    mutate(
      high_conf = median_prob > conf_thresh,
      centered_log2_count = log2(n / median(n))
    )
  ###plotting code, want to make sure that classes that are enriched
  ###e.g. above or below median threshold are colored blue/distinguished in some way
  plot <- ggplot(summary_df, aes(
    x = centered_log2_count,
    y = reorder(!!sym(class_col), centered_log2_count),
    fill = high_conf
  )) +
    geom_col() +
    geom_text(aes(label = paste0("n=", n)),
              hjust = ifelse(summary_df$centered_log2_count > 0, -0.1, 1.1),
              size = 3,
              color = "black") +
    geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
    scale_fill_manual(values = c("TRUE" = "blue", "FALSE" = "grey70")) +
    labs(
      title = paste0("Class Enrichment for ", class_col),
      x = expression(log[2]*"(count / median count)"),
      y = class_col,
      fill = paste0("Median prob > ", conf_thresh)
    ) +
    theme_minimal(base_size = 14) +
    coord_cartesian(clip = "off") +
    theme(
      legend.position = "none",
      plot.margin = margin(10, 40, 10, 10)
    )
  
  return(list(plot = plot, data = summary_df))
}

#get data for an  plotting 
# results <- plot_class_enrichment(df_free_clean, "ClassyFire.superclass", "ClassyFire.superclass.probability")
# head(results$data)
plots_free <- list()

for (cols in classification_cols) {
  class_col <- cols[1]
  prob_col <- cols[2]
  
  p <- plot_class_enrichment(df_free_clean, class_col, prob_col)
  print(p)  # Show plot in console
  
  # Save plots in a named list
  plots_free[[class_col]] <- p
}
setwd("/Users/apulvino/serum_metabolomics/")
for (name in names(plots_free)) {
  this_plot <- plots_free[[name]][["plot"]]
  filename <- paste0("plot_free_", name, ".png")
  
  message("Saving: ", filename)
  
  ggsave(
    filename = filename,
    plot = this_plot,
    width = 8,
    height = 6,
    dpi = 300
  )
}

############### i feel like these are all kind of giving me the same basic result -- differentially abundant classes include carboxylic acids; fatty acids; amino acids .... going to go ahead and take the bio results (also happens to have the most observations/annotations) for a run of FELLA

```



FELLA on run of SIRIUS
```{r}

library(tidyverse)
library(stats)
library(ggplot2)
library(scales)
library(FELLA)
library(readr)
library(igraph)
library(ggraph)
####### could do a merge with the tidymass obj to try to extract more group-wise info from SIRIUS run, but 
####### i think we're fine enough from the FELLA+tidymass annotated run unless reviewers/katie says otherwise
##download from SIRIUS run on quest to computer
# canopus_formula <- read_tsv("/Users/apulvino/serum_metabolomics/canopus_formula_summary.tsv")
# 
##Clean Canopus ID to isolate mappingFeatureId
# canopus_clean <- canopus_formula %>%
#   mutate(variable_id = str_remove(mappingFeatureId, ".*UNKNOWN_"))
# canopus_clean
# 
##Merge with tidymass object using mappingFeatureId == alignedFeatureId
# merged <- left_join(object@variable_info, canopus_clean, by = "variable_id")
###########################################################################################
###### FELLA RUN ON SIRIUS KEGG ANNO OUTPUT (DB-FREE MODE)
sirius_kegg <- read_tsv("/Users/apulvino/serum_metabolomics/sirius_results/dualion_structure_identifications_all.tsv")
confident_kegg_foreground <- sirius_kegg %>% 
  filter(links %like% "KEGG" & SiriusScoreNormalized >= 1) %>% 
  pull(links) %>%
  sub(".*KEGG:\\(([^)]+)\\).*", "KEGG:\\1", .) %>%
  gsub("KEGG:", "\\1", .)
kegg_background <- sirius_kegg %>%
  filter(links %like% "KEGG" #& SiriusScoreNormalized > 0.9
                                                    ) %>%
  pull(links) %>%
  sub(".*KEGG:\\(([^)]+)\\).*", "KEGG:\\1", .)%>%
  gsub("KEGG:", "\\1", .)
 fella.db <- loadKEGGdata(databaseDir = "fella_mmu", loadMatrix = c("hypergeom", "diffusion", "pagerank"),
                          internalDir = TRUE)
#method <- "pagerank"
## need to use diffusion if you're running simulation/monte carlo approx!!!; mc did not work for this data/gave no results
method <- "diffusion"
nlimit <- 250
fella.data <- defineCompounds(#compounds = confident_kegg_foreground,
                              compounds = unlist(strsplit(confident_kegg_foreground, "\\s+") %>% na.omit()),
                              #compoundsBackground = kegg_background,
                              compoundsBackground = unlist(strsplit(kegg_background, "\\s+")%>% na.omit()),
                              data = fella.db)
fella.analysis_mutual <- enrich(#compounds = confident_kegg_foreground, 
                                compounds = unlist(strsplit(confident_kegg_foreground, "\\s+")%>% na.omit()),
                                #compoundsBackground = kegg_background,
                                compoundsBackground = unlist(strsplit(kegg_background, "\\s+")%>% na.omit()),
                                method = method,
                                approx = "gamma",
                                data = fella.db,
                                )

results_sirius <- generateResultsTable(object = fella.analysis_mutual, data = fella.db, 
                                   method = method,
                                   nlimit = nlimit)
results_sirius$adj_pScore <- p.adjust(results_sirius$p.score, method = "BH")

enriched_subgraph <- generateResultsGraph(object = fella.analysis_mutual, data = fella.db, threshold = 0.05,
                                          method = method,
                                          nlimit = nlimit)
#plotGraph(enriched_subgraph)
# Extract node data with significance
node_data <- results_sirius %>%
  filter(KEGG.id %in% V(enriched_subgraph)$name) %>%
  transmute(
    name = KEGG.id,
    p.score,
    log10_p_score = -log10(p.score),
    label_text = KEGG.name
  )
##################################
g_tidy <- as_tbl_graph(enriched_subgraph) %>%
  left_join(node_data, by = "name") %>%
  mutate(
    label_text = ifelse(is.na(label_text), name, label_text),
    degree = centrality_pagerank(directed = FALSE),
    highlight = degree >= quantile(degree, 0.7, na.rm = TRUE),
    label_to_show = ifelse(highlight, label_text, NA)
  ) %>%
  activate(edges) %>%
  mutate(edge_highlight = .N()$highlight[from] & .N()$highlight[to]
         )
g <- ggraph(g_tidy, layout = "stress") +
  geom_edge_link(color = "gray90", edge_width = 1.5) +
  geom_node_point(color = "gray90", size = 4) +
  geom_edge_link(aes(filter = edge_highlight), color = "dodgerblue2", edge_width = 1.5) +
  geom_node_point(aes(filter = highlight, size = log10_p_score), color = "dodgerblue3", size = 4,
                  ) +
  geom_node_text(aes(filter = highlight, label = label_to_show),
                 color = "black", fontface = "bold",
                 repel = TRUE, max.overlaps = 50, size = 6.5,
                 box.padding = 1.5, point.padding = 1, segment.size = 0.4) +
  scale_size_continuous(
    name = expression(-log[10](italic(p)*"-score")),
    range = c(4, 14)) +
  theme_void(base_size = 20) +  # boost all text elements
  labs(title = "FELLA Enriched Pathway Network", subtitle = "", size = "-log10(p-score)") +
  theme(legend.position = "none",
        plot.title = element_text(size = 26, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 20),
        panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA)
  )
## used external browser tool to convert to png to get into google slides
ggsave("fella_network_wide.png", plot = g,
       width = 100, height = 60, units = "cm",
       dpi = 600, device = "png")

# hist(results_mutual%>% filter(Entry.type== "pathway") %>% pull(p.score), breaks = 100, main = "Diffusion P-Score Distribution")
# lets plot those pathways
results_sirius %>%
  filter(p.score < 0.05 & Entry.type == "pathway") %>%
  slice_min(order_by = p.score, n = 20) %>%
  ggplot(aes(x = reorder(KEGG.name, -p.score), y = -log10(p.score))) +
  geom_col(fill = "blue") +
  coord_flip() +
  labs(
    title = "Top Enriched Pathways",
    x = "Pathway",
    y = expression(-log[10]~"(P-score)")
  ) +
  theme_minimal(base_size = 14)

```





```{r, preparing objects for viz, echo = FALSE, message = FALSE, warning=FALSE}
# extract individual groups needed for both case studies
sqm_id =
  object %>%
  activate_mass_dataset(what = "sample_info") %>%
  filter(group == "sqm") %>%
  pull(sample_id)

hum_id = 
  object %>%
  activate_mass_dataset(what = "sample_info") %>%
  filter(group == "hum") %>%
  pull(sample_id)

mac_id = 
  object %>%
  activate_mass_dataset(what = "sample_info") %>%
  filter(group == "mac") %>%
  pull(sample_id)

```





```{r, preparing the humsqmVmac object, echo = FALSE, message = FALSE, warning=FALSE}

################ Creating the object
### CASE 1: humsqm vs. mac outgroup
#object@expression_data[is.na(object@expression_data)] <- 0
obj_sqmac <- 
  mutate_fc(object = object,
            control_sample_id = sqm_id, 
            case_sample_id = mac_id,
            mean_median = "median")
## 4 outgroup mac samples.
## 18 humans and macs case samples.
groups_to_keep <- c("sqm", "mac")
obj_sqmac <- obj_sqmac %>%
  activate_mass_dataset("sample_info") %>%
  filter(group %in% groups_to_keep)


```






## Case Study 1: squirrel monkey vs. macaque
In this case the squirrel monkey treatments are combined into one control and macaque is the outgroup.


```{r, heatmap for humsqmVmac, echo = FALSE, message = FALSE, warning=FALSE}

#set.seed(100)
### CASE 2: humsqm vs. mac outgroup
### Calculate p-values
object_sqmac <- 
  mutate_p_value(
    object = obj_sqmac,
    control_sample_id = sqm_id,
    case_sample_id = mac_id,
    method = "wilcox.test",
    p_adjust_methods = "BH"
    )

# diff_metabolites <-
#   object_humsqm %>% 
#   activate_mass_dataset(what = "variable_info") %>% 
#   filter(p_value_adjust < 0.1) %>% 
#   extract_variable_info()

diff_metabolites.sm.s <-
  object_sqmac %>% 
  activate_mass_dataset(what = "variable_info") %>% 
  extract_variable_info() %>%
  filter(!is.na(Compound.name) & p_value_adjust < 0.1)# %>%
  #filter(na_freq < 0.2 | na_freq_2 < 0.2) %>% 
  #filter(Total.score > 0.9 & fc < 0.2 | fc > 2)
 
########## No need to run this since we did it for MetabolomicsFinalReport.Rmd and only needs to be run once to get reference chebi information
# library(webchem)
library(jsonlite)
library(httr)
library(jsonlite)
library(purrr)
library(furrr)
# We download and read in chebi.obo ontology file
# https://obofoundry.org/ontology/chebi.html
# library(webchem)
library(httr)
library(jsonlite)
library(purrr)
library(furrr)
library(future)
getChebi_Ont <- function(chebi_ids) {
  results <- list()
  for (ID in seq_along(chebi_ids)) {
    response <- GET(paste0("https://www.ebi.ac.uk/chebi/beta/api/public/compound/", 
                           URLencode(chebi_ids[[ID]],
                            reserved = TRUE)
                  ),
                  accept("application/json"))
    if (status_code(response) == 200) {
      results[[chebi_ids[[ID]]]] <- httr::content(response, as = "parsed", encoding = "UTF-8")
    } else {
      warning(sprintf("Failed to fetch %s (status %d)", chebi_ids[[ID]], status_code(response)))
      results[[chebi_ids[[ID]]]] <- NULL
    }
  }
  return(results)
}
chebi_results.sm <- getChebi_Ont(diff_metabolites.sm.s$Lab.ID)
# recursive find for any of the terms at any level nested in list of listed ont output
chebi_bio.sm <- keep(chebi_results.sm, ~
    !any(grepl(
    paste(c("dye", "synthetic", "artificial", "non-natural",
            "non-endogenous", "contaminant", "preservative", "disinfectant", "industrial", "agriculture", "insecticide"  ,"triazole", "acetanilide", "hydrochloride", "benzamide", 
  "phenacetin", "prodrug", "API", "pharmaceutical", "inhibitor", 
  "agonist", "antagonist", "PEG", "pyrrolidine", "piperidine", 
  "aniline", "toxicant", "xenobiotic", "organophosphate"),
          collapse = "|"), .x, ignore.case = TRUE)) 
     
)
Natdiff_metabolites.sm.s <- diff_metabolites.sm.s %>%
  filter(Lab.ID %in% names(chebi_bio.sm) |
    str_detect(Lab.ID, "shen|HILIC|NO|HMDB|hmdb|fiehn|^C[0-9]+"))
readr::write_csv(Natdiff_metabolites.sm.s,
                file = "/Users/apulvino/serum_metabolomics/stat_analysis/Natdiff_sqmac_metabolites.csv")
Natdiff_metabolites.sm.s <- read.csv("/Users/apulvino/serum_metabolomics/stat_analysis/Natdiff_sqmac_metabolites.csv")

metabo_heatmap.sm <-
  Natdiff_metabolites.sm.s %>%
   filter(p_value_adjust < 0.1 & abs(fc) > 1)

heat_object <- 
object_sqmac %>% 
  activate_mass_dataset(what = "sample_info") %>% 
  filter(sample_id %in% c(sqm_id, mac_id)) %>% 
  activate_mass_dataset(what = "variable_info") %>% 
  filter(variable_id %in% metabo_heatmap.sm$variable_id) %>% 
  `+`(1) %>% 
  log(2) %>% 
  scale()
library(ComplexHeatmap)
#h1 <- HeatmapAnnotation(class = extract_sample_info(temp_object)$group)
h1 <- HeatmapAnnotation(
  `Donor Group` = anno_simple(extract_sample_info(heat_object)$group, pch = c(str_extract(extract_sample_info(heat_object)$group,"^[a-z]")),
                              col = c("mac"="#a6761d","sqm"="#666666"),
                              pt_gp = gpar(col = "white"))
  )

# PAPER 1
## had to take a screenshot of the tiff to get it into google slides
heat_object@variable_info = extract_variable_info(heat_object) %>% drop_na(Compound.name)
heat_object <- update_mass_dataset(heat_object)
#png("qual2metaboheatmap_ser.png", units="in", width=8.5, height=5, res=300)
massstat::Heatmap(matrix = heat_object, 
                  name = "z-score", 
                  #color_space = "HUE",
                  row_names_gp = gpar(cex = 0.4, fontsize = 15),
                  column_names_gp = gpar(cex = 0.2, fontsize = 30),
                  column_names_rot = 45,
                  top_annotation = h1, 
                  row_labels = heat_object@variable_info$Compound.name,
                  border = TRUE,
                  #column_labels = rep("",23),
                  show_column_dend = FALSE,
                  show_row_dend = FALSE 
                  #column_labels = temp_object@sample_info$subject_id
                  )

#dev.off()

```


```{r, volcano plot for humsqmVmac, echo = FALSE, message = FALSE, warning=FALSE}

options(ggrepel.max.overlaps = Inf)
library(ggrepel)
temp_object <- heat_object
#tiff("qual2metabvolc.tiff", units="in", width=25, height=8.5, res=300)
temp_object@variable_info$Compound.name.1 <- temp_object@variable_info$Compound.name
volcano_plot(object = temp_object,
             add_text = TRUE,
             text_from = "Compound.name.1",
             p_value_cutoff = 0.05)
#dev.off()
# readr::write_csv(diff_metabolites.sm.s, 
#                  file = "/Users/apulvino/serum_metabolomics/stat_analysis/diff_sqmac_metabolites.csv")
print(Natdiff_metabolites.sm.s[,c(6,7,8,9)])

### SQMAC PERMANOVA
### just make sure you have metadata first, run cecal_shotgun.Rmd first 2 blocks and that will give you metadata2 variable needed
###  determine significance of term "group" effect between sqm and mac 
dimnames <- c("mac01","mac02","mac03","mac04","mac05","mac06","mac07",
              "mac08","sqm10","sqm11","sqm12",
              "sqm13","sqm16","sqm17",
              "sqm18")
 sample_distance <-
   as.matrix(dist_mass_dataset(x = temp_object, margin = "sample", method = "manhattan"))
# rownames(sample_distance) <- dimnames
# colnames(sample_distance) <- dimnames
result <- metadata2 %>% filter(!sample %in% c("sqm9","sqm14", "sqm15") & !group %in% "hum")
mat_cleaned <- sample_distance[
  !grepl("Ben-Ant-20240228-09|Ben-Ant-20240228-1[4-5]|Ben-Ant-20240228-2[5-6]", rownames(sample_distance)),
  !grepl("Ben-Ant-20240228-09|Ben-Ant-20240228-1[4-5]|Ben-Ant-20240228-2[5-6]", colnames(sample_distance)),
  drop = FALSE
]
print("squirrel monkey- vs. macaque-donor serum metabolome permanova")
adonis2(mat_cleaned ~ group, data = result)

```



```{r, echo = FALSE, message = FALSE, warning=FALSE}

library(ggraph)
library(tidygraph)
graph_data_sqmac <-
  convert_mass_dataset2graph(
    object = temp_object,
    margin = "variable",
    cor_method = "spearman",
    p_adjust_cutoff = 0.05,
    p_value_cutoff = 0.05,
    pos_cor_cutoff = 0.5,
    neg_cor_cutoff = -0.5
  ) %>% 
  mutate(Degree = centrality_degree(mode = 'all'))
#rm(list = "temp_object")
#gc()
#install.packages("extrafont")
#install.packages("shadowtext")
library(extrafont)
library(shadowtext)
loadfonts()
plot <- 
ggraph(graph = graph_data_sqmac, layout = "kk") +
  geom_edge_fan(aes(color = correlation,
                    width = -log(p_value, 10)),
                show.legend = TRUE) +
  geom_node_point(aes(size = Degree)) +
  shadowtext::geom_shadowtext(aes(x = x, y = y,
                                  label = Compound.name.x),
                              bg.colour = "white",
                              colour = "black")+
  theme_graph() +
  scale_edge_color_gradient2(low = "darkblue", mid = "white", high = "red")
plot

```





```{r, kegg, echo = FALSE, message = FALSE}

### what's the difference bw pagerank and diffusion for projection you ask?
### you have to increase nlimit by like 100 and then you get more than one nodes
### the few you get include taurine and hypotaurine metabolism, with page rank you get 
### bile secretion and taurine metabolism-- processes that actually make sense together 
### incidentally we also pick up SCFAs in these projections... something we have more refined empirical evidence for in previous analysis targeted metabolomics data published last year
#### hypergeom is too sparse
nlimit <- 250
method <- "pagerank"

setwd("/Users/apulvino/serum_metabolomics/")
library(FELLA)
#keggraph <- buildGraphFromKEGGREST("mmu")
## only needs to be run once; might take a while the first time... expect to wait maybe 15-25 min
#buildDataFromGraph(keggdata.graph = keggraph, databaseDir = "fella_mmu", matrices = c("hypergeom", "diffusion", "pagerank"), internalDir = TRUE)
 fella.db <- loadKEGGdata(databaseDir = "fella_mmu",
                          loadMatrix = c("hypergeom", "diffusion", "pagerank"),
                          internalDir = TRUE)
fella.data <- defineCompounds(compounds = Natdiff_metabolites.sm.s$KEGG.ID,
                              compoundsBackground = diff_metabolites.sm.s$KEGG.ID,
                              data = fella.db)
fella.analysis_sm <- enrich(compounds = Natdiff_metabolites.sm.s$KEGG.ID,
                            compoundsBackground =  diff_metabolites.sm.s$KEGG.ID,
                            method = FELLA::listMethods(),
                            #method = "diffusion",
                            data = fella.db)
results_sm <- generateResultsTable(object = fella.analysis_sm, data = fella.db, 
                                   method = method, nlimit = nlimit)
#results_sm$adj_pScore <- p.adjust(results_sm$p.score, method = "BH")

enriched_subgraph <- generateResultsGraph(object = fella.analysis_sm, data = fella.db,threshold = 0.05,
                                          method = method, nlimit = nlimit)
# g.go <- addGOToGraph(
#   graph = enriched_subgraph,
#   GOterm = "GO:0002152",
#   godata.options = list(annoDb = "org.Mm.eg.db", ont = "CC"),
#   mart.options = list(biomart = "ensembl", dataset = "mmusculus_gene_ensembl"))
plotGraph(enriched_subgraph)


```




## Case Study 2: humans vs macaques


```{r, preparing the humVmac object, echo = FALSE}

################ Creating the object
### CASE 2: sqm vs. mac outgroup
obj_humac <- 
  mutate_fc(object = object,
            control_sample_id = hum_id,
            case_sample_id = mac_id,
            mean_median = "median")
## 4 outgroup mac samples.
## 18 humans and macs case samples.
groups_to_keep <- c("hum", "mac")
obj_humac <- obj_humac %>%
  activate_mass_dataset("sample_info") %>%
  filter(group %in% groups_to_keep)

```


```{r, heatmap for sqmVmac, echo = FALSE}

#set.seed(100)
### CASE 2: humsqm vs. mac outgroup
### Calculate p-values
object_humac <- 
  mutate_p_value(
    object = obj_humac,
    control_sample_id = hum_id,
    case_sample_id = mac_id,
    method = "wilcox.test",
    p_adjust_methods = "BH"
    )

diff_metabolites.hm.s <-
  object_humac %>% 
  activate_mass_dataset(what = "variable_info") %>% 
  extract_variable_info() %>%
  filter(!is.na(Compound.name) & p_value_adjust < 0.1) #%>%
  #filter(na_freq < 0.2 | na_freq_2 < 0.2) %>% 
  #filter(Total.score > 0.9 & fc < 0.4 | fc > 3)

library(httr)
library(jsonlite)
library(purrr)
library(furrr)
library(future)
getChebi_Ont <- function(chebi_ids) {
  results <- list()
  for (ID in seq_along(chebi_ids)) {
    response <- GET(paste0("https://www.ebi.ac.uk/chebi/beta/api/public/compound/", 
                           URLencode(chebi_ids[[ID]],
                            reserved = TRUE)
                  ),
                  accept("application/json"))
    if (status_code(response) == 200) {
      results[[chebi_ids[[ID]]]] <- httr::content(response, as = "parsed", encoding = "UTF-8")
    } else {
      warning(sprintf("Failed to fetch %s (status %d)", chebi_ids[[ID]], status_code(response)))
      results[[chebi_ids[[ID]]]] <- NULL
    }
  }
  return(results)
}
chebi_results.hms <- getChebi_Ont(diff_metabolites.hm.s$Lab.ID)
# recursive find for any of the terms at any level nested in list of listed ont output
chebi_bio.hms <- keep(chebi_results.hms, ~
    !any(grepl(
    paste(c("dye", "synthetic", "artificial", "non-natural",
            "non-endogenous", "contaminant", "preservative", "disinfectant", "industrial", "agriculture", "insecticide"  ,"triazole", "acetanilide", "hydrochloride", "benzamide", 
  "phenacetin", "prodrug", "API", "pharmaceutical", "inhibitor", 
  "agonist", "antagonist", "PEG", "pyrrolidine", "piperidine", 
  "aniline", "toxicant", "xenobiotic", "organophosphate"),
          collapse = "|"), .x, ignore.case = TRUE)) 
     
)
Natdiff_metabolites.hm.s <- diff_metabolites.hm.s %>%
  filter(Lab.ID %in% names(chebi_bio.hms) |
    str_detect(Lab.ID, "shen|HILIC|NO|HMDB|hmdb|fiehn|^C[0-9]+"))
readr::write_csv(Natdiff_metabolites.hm.s,
                file = "/Users/apulvino/serum_metabolomics/stat_analysis/Natdiff_humac_metabolites.csv")
Natdiff_metabolites.hm.s <- read.csv("/Users/apulvino/serum_metabolomics/stat_analysis/Natdiff_humac_metabolites.csv")

metabo_heatmap.hm <-
  Natdiff_metabolites.hm.s %>%
   filter(p_value < 0.05) %>%
   filter(p_value_adjust < 0.1) %>%
  filter(fc <= 0.75 | fc >= 1.3) %>%
  filter(na_freq < 0.2 | na_freq_2 < 0.2) %>% 
  filter(Total.score > 0.9 #| SS > 0.7
         )


heat_object <- 
object_humac %>% 
  activate_mass_dataset(what = "sample_info") %>% 
  filter(sample_id %in% c(hum_id, mac_id)) %>% 
  activate_mass_dataset(what = "variable_info") %>% 
  filter(variable_id %in% metabo_heatmap.hm$variable_id) %>% 
  `+`(1) %>% 
  log(2) %>% 
  scale()
library(ComplexHeatmap)

h1 <- HeatmapAnnotation(
  `Donor Group` = anno_simple(extract_sample_info(heat_object)$group, pch = c(str_extract(extract_sample_info(heat_object)$group,"^[a-z]")),
                              col = c("mac"="#a6761d","sqm"="#666666","hum"="#1b9e77"),
                              pt_gp = gpar(col = "white"))
  )

# temp_object@variable_info = extract_variable_info(temp_object) %>%
#   mutate(Compound.name = 
#            ifelse(Compound.name == "Acetaminophen",
#                   paste(variable_id, mz, rt, sep = "_"),
#                   Compound.name)
#          )

# PAPER 1
#png("qual2metaboheatmap_cec.png", units="in", width=8.5, height=5, res=300)
massstat::Heatmap(matrix = heat_object, 
                  name = "z-score",
                  #color_space = "Dark2",
                  row_names_gp = gpar(cex = 0.4, fontsize = 15),
                  column_names_gp = gpar(cex = 0.2, fontsize = 30),
                  column_names_rot = 45,
                  top_annotation = h1,
                  row_labels = heat_object@annotation_table$Compound.name,
                  border = TRUE,
                  #column_labels = rep("",24),
                  show_column_dend = FALSE,
                  show_row_dend = FALSE
                  #column_labels = temp_object@sample_info$subject_id
                  ) 

#dev.off()

```



```{r, volcano plot for humVmac, echo = FALSE, message = FALSE}

temp_object <- heat_object
options(ggrepel.max.overlaps = Inf)
library(ggrepel)
temp_object@variable_info$Compound.name.1 <- temp_object@variable_info$Compound.name
#tiff("qual2metabvolc.tiff", units="in", width=8.5, height=8.5, res=300)
volcano_plot(object = temp_object,
             add_text = TRUE,
             text_from = "Compound.name",
             p_value_cutoff = 0.05
             )
#dev.off()
# readr::write_csv(diff_metabolites.hm.s, 
#                  file = "/Users/apulvino/serum_metabolomics/stat_analysis/diff_hummac_metabolites.csv")
print(Natdiff_metabolites.hm.s[,c(6,7,8,9)])

### HUMAC PERMANOVA
### just make sure you have metadata first, run cecal_shotgun.Rmd first 2 blocks and that will give you metadata2 variable needed
###  determine significance of term "group" effect between sqm and mac 
dimnames <- c("mac01","mac02","mac03","mac04","mac05","mac06","mac07",
              "mac08", "hum19", "hum20","hum21","hum22","hum23","hum24")
 sample_distance <-
   as.matrix(dist_mass_dataset(x = temp_object, margin = "sample", method = "manhattan"))
# rownames(sample_distance) <- dimnames
# colnames(sample_distance) <- dimnames
result <- metadata2 %>% filter(!sample %in% c("sqm9","sqm14", "sqm15", "hum25", "hum26") & !group %in% "sqm")
mat_cleaned <- sample_distance[
  !grepl("Ben-Ant-20240228-09|Ben-Ant-20240228-1[0-8]|Ben-Ant-20240228-2[5-6]", rownames(sample_distance)),
  !grepl("Ben-Ant-20240228-09|Ben-Ant-20240228-1[0-8]|Ben-Ant-20240228-2[5-6]", colnames(sample_distance)),
  drop = FALSE
]
print("human- vs. macaque-donor serum metabolome permanova")
adonis2(mat_cleaned ~ group, data = result)


```



```{r, echo = FALSE, message = FALSE}

library(ggraph)
library(tidygraph)
graph_data_humac <-
  convert_mass_dataset2graph(
    object = temp_object,
    margin = "variable",
    cor_method = "spearman",
    p_adjust_cutoff = 0.05,
    p_value_cutoff = 0.05,
    pos_cor_cutoff = 0.5,
    neg_cor_cutoff = -0.5
  ) %>% 
  mutate(Degree = centrality_degree(mode = 'all'))
#rm(list = "temp_object")
#gc()
#install.packages("extrafont")
#install.packages("shadowtext")
library(extrafont)
library(shadowtext)
library(ggraph)
loadfonts()
plot <- 
ggraph(graph = graph_data_humac, layout = "kk") +
  geom_edge_fan(aes(color = correlation,
                    width = -log(p_value, 10)),
                show.legend = TRUE) +
  geom_node_point(aes(size = Degree)) +
  shadowtext::geom_shadowtext(aes(x = x, y = y,
                                  label = Compound.name
                                  ),
                              bg.colour = "white",
                              colour = "black")+
  theme_graph() +
  scale_edge_color_gradient2(low = "darkblue", mid = "white", high = "red")
plot

```



```{r, kegg, echo = FALSE, message = FALSE}

setwd("/Users/apulvino/serum_metabolomics/")
library(FELLA)
# fella_hsa or fella_mmu can be used :) 
## mmu end up working much better for obvious reasons
#keggraph <- buildGraphFromKEGGREST("mmu")
## only needs to be run once; might take a while the first time... expect to wait maybe 15-25 min
#buildDataFromGraph(keggdata.graph = keggraph, databaseDir = "fella_mmu", matrices = c("hypergeom", "diffusion", "pagerank"), internalDir = TRUE)
# fella.db <- loadKEGGdata(databaseDir = "fella_mmu", loadMatrix = c("hypergeom", "diffusion", "pagerank"),
#                          internalDir = TRUE)
fella.data <- defineCompounds(compounds = Natdiff_metabolites.hm.s$KEGG.ID,
                              compoundsBackground = diff_metabolites.hm.s$KEGG.ID,
                              data = fella.db)
fella.analysis_hm <- enrich(compounds = Natdiff_metabolites.hm.s$KEGG.ID,
                            compoundsBackground = diff_metabolites.hm.s$KEGG.ID,
                            method = FELLA::listMethods(),
                            #method = "diffusion",
                            data = fella.db)
results_hm <- generateResultsTable(object = fella.analysis_hm, data = fella.db, 
                                   method = method, nlimit = nlimit)
results_hm$adj_pScore <- p.adjust(results_hm$p.score, method = "BH")

enriched_subgraph <- generateResultsGraph(object = fella.analysis_hm, data = fella.db,threshold = 0.05,
                                          method = method,nlimit = nlimit)
# g.go <- addGOToGraph(
#   graph = enriched_subgraph,
#   GOterm = "GO:0002152",
#   godata.options = list(annoDb = "org.Mm.eg.db", ont = "CC"),
#   mart.options = list(biomart = "ensembl", dataset = "mmusculus_gene_ensembl"))
plotGraph(enriched_subgraph)


```




## Mutual compound run of sirius 


```{r}
## determining mutually differentially abundant pathways/compounds

####.     KEGG path enrichment
################   PAPER 1   KEGG path enrichment    ###########################
#keggraph <- buildGraphFromKEGGREST("mmu")
## only needs to be run once; might take a while the first time... expect to wait maybe 15-25 min
#buildDataFromGraph(keggdata.graph = keggraph, databaseDir = "fella_mmu", matrices = c("hypergeom", "diffusion", "pagerank"), internalDir = TRUE)

# fella.db <- loadKEGGdata(databaseDir = "fella_mmu", loadMatrix = c("hypergeom", "diffusion", "pagerank"),
#                          internalDir = TRUE)
method <- "pagerank"
#method <- "diffusion"
nlimit <- 250
fella.data <- defineCompounds(compounds = intersect(Natdiff_metabolites.sm.s$KEGG.ID,
                                              Natdiff_metabolites.hm.s$KEGG.ID),
                          compoundsBackground = c(diff_metabolites.hm.s$KEGG.ID,
                                                 diff_metabolites.sm.s$KEGG.ID),
                              data = fella.db)
fella.analysis_mutual <- enrich(compounds = intersect(Natdiff_metabolites.sm.s$KEGG.ID,
                                              Natdiff_metabolites.hm.s$KEGG.ID), 
                              compoundsBackground = c(diff_metabolites.hm.s$KEGG.ID,
                                                 diff_metabolites.sm.s$KEGG.ID),
                            #method = FELLA::listMethods(),
                            #method = "pagerank",
                            method = method,
                            approx = "gamma",
                            data = fella.db)

results_mutual <- generateResultsTable(object = fella.analysis_mutual, data = fella.db, 
                                   method = method,
                                   nlimit = nlimit)
results_mutual$adj_pScore <- p.adjust(results_mutual$p.score, method = "BH")

enriched_subgraph <- generateResultsGraph(object = fella.analysis_mutual, data = fella.db,
                                          threshold = 0.05,
                                          method = method,
                                          nlimit = nlimit)

#plotGraph(enriched_subgraph)
# Extract node data with significance
#plotGraph(enriched_subgraph)
# Extract node data with significance
node_data <- results_mutual %>%
  filter(KEGG.id %in% V(enriched_subgraph)$name) %>%
  transmute(
    name = KEGG.id,
    p.score,
    log10_p_score = -log10(p.score),
    label_text = KEGG.name
  )
##################################
g_tidy <- as_tbl_graph(enriched_subgraph) %>%
  left_join(node_data, by = "name") %>%
  mutate(
    label_text = ifelse(is.na(label_text), name, label_text),
    degree = centrality_pagerank(),
    highlight = degree >= quantile(degree, 0.7, na.rm = TRUE),
    label_to_show = ifelse(highlight, label_text, NA)
  ) %>%
  activate(edges) %>%
  mutate(edge_highlight = .N()$highlight[from] & .N()$highlight[to]
         )
g <- ggraph(g_tidy, layout = "stress") +
  geom_edge_link(color = "gray90", edge_width = 0.5) +
  geom_node_point(color = "gray90", size = 5) +
  geom_edge_link(aes(filter = edge_highlight), color = "#e6ab02", edge_width = 2) +
  geom_node_point(aes(filter = highlight, size = log10_p_score), color = "#e6ab02") +
  geom_node_text(
    aes(filter = highlight, label = label_to_show),
    color = "black",
    fontface = "bold",
    repel = TRUE,
    max.overlaps = 50,         # show all possible labels
    size = 7,                   # bump up text size
    box.padding = 1.5,
    point.padding = 1,
    segment.size = 0.4
  ) +
  scale_size_continuous(
    name = expression(-log[10](italic(p)*"-score")),
    range = c(4, 14)            # scale node size larger
  ) +
  theme_void(base_size = 20) +  # boost all text elements
  labs(
    title = "TidyMass-Annotated Enriched Pathway Network",
    subtitle = "",
    size = "-log10(p-score)"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 26, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 20)
  )
ggsave("/Users/apulvino/serum_metabolomics/tidyanno_network_wide.png", plot = g,
       width = 70, height = 45, dpi = 600, units = "cm", bg = "white")

# hist(results_mutual%>% filter(Entry.type== "pathway") %>% pull(p.score), breaks = 100, main = "Diffusion P-Score Distribution")
# lets plot those pathways
results_mutual %>%
  filter(p.score < 0.05 & Entry.type == "pathway") %>%
  slice_min(order_by = p.score, n = 20) %>%
  ggplot(aes(x = reorder(KEGG.name, -p.score), y = -log10(p.score))) +
  geom_col(fill = "#E6AB02FF") +
  coord_flip() +
  labs(
    title = "Top Enriched Pathways",
    x = "Pathway",
    y = expression(-log[10]~"(P-score)")
  ) +
  theme_minimal(base_size = 14)


```


